### ISSUE TITLE
Can you provide the results.csv in plot_rdcurve.py?

### ISSUE THREAD

**Issue by 543350391** [kktsubota/universal-dic#6]
I have run the plot_rdcurve.py but there are some missing files in Line 104~Line110. Could you please share it with me? Thank you!
https://github.com/kktsubota/universal-dic/blob/e931bb0047e554fb99367ee9bd19c796f16dedce/plot_rdcurve.py#L104

**Comment by kktsubota** [comment]
You need to run our code following the instruction in the README file to obtain these files.
I did not plan to provide the files, but I will provide the results for our method if you want.

**Comment by 543350391** [comment]
Thank you for your quick reply. I would be very grateful if you could provide your results. I will run the code to obtain the rest files!

**Comment by kktsubota** [comment]
I added the results in `results/ours/wacnn`.
